### ISSUE TITLE
Pass stream to validator for reporting

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator#24]
Allow calling code that creates a pipeline to pass in a writable stream for reporting (as an option).

If such a stream is passed in, the reporting code will use this to write report data into.

@rgrp (cc @tryggvib) question:

In such a case, what should be the format of the report?

The **current default behaviour** of the report module is to maintain a stream over a YAML file (YAML objects are append friendly). The reporter also supports an SQLite backend via https://github.com/pudo/dataset

In the case of this passed-in stream, I'm thinking line-delimited JSON objects (as YAML would require additional dependencies for the calling code) might be the most useful?

**Comment by rgrp** [comment]
Yes, as per US I recommend we use JSON (and can use line-delimited) but frankly I'm happy with the simplest thing possible even if not that nice for streaming.
