### ISSUE TITLE
Do all CI on Travis

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator#27]
OKFN has an account there, and other projects are there. 

Depends on #26

**Comment by tryggvib** [comment]
You should be able to remove Shippable now.

**Comment by pwalsh** [comment]
Ok, I'm keeping shippable in anyway to test my forks. 

It is interesting comparing both. Apart from the various config setup issues etc, false positives are ~ frequent on Travis (e.g.: https://travis-ci.org/okfn/tellme/jobs/50107956 and https://travis-ci.org/okfn/tabular-validator/jobs/50104602)
