### ISSUE TITLE
If XLS, try to load data anyway?

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator#29]
And add a warning about it to the report.

**Comment by pwalsh** [comment]
@rgrp @tryggvib (this is not high priority task, but I'm adding the question here anyway while fresh in my head) 

Question: If we get an Excel file, and open it, what should actually be done assuming multiple worksheets?

My assumption is that multiple worksheets would be a new use case to treat later (e.g.: run a pipeline per worksheet; allow user to give data for which worksheets are relevant, etc.)

However, seeing as this issue is added as a simple convenience, I'd suggest that what we might want here for a first iteration is:

* open the excel file
* parse the first worksheet as CSV for out data
* that's it

**Comment by rgrp** [comment]
You'll need sheetnum argument (and default to sheet 1). See dataconverters cli api ;-)

**Comment by pwalsh** [comment]
I'm adding XLS support in this sprint, but not guessing format - the user needs to declare that the format is xls. 

In this case, I'm not raising a warning about it.
