### ISSUE TITLE
Change the name?

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator#41]
Tabular Validator is not a great - it is not even that description seeing as we are actually working towards **validation** (or, linting) and optional **transformation** (or, cleaning) of data.

I don' have any suggestions right now, just putting it out there.

**Comment by tryggvib** [comment]
Here's a late night braindump:

* tablecheckers
* tabcheck
* tablecleaner
* csv-proofreader
* csvexam
* tablefixer
* tabfix
* tablemechanic
* bobbytables

**Comment by pwalsh** [comment]
We've decided on "Good tables".

Good tables == Good times!
