### ISSUE TITLE
Travis false positives

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator#43]
@tryggvib @rgrp 

A question:

Seeing as OK is using Travis regularly, are false positives a common occurrence?

eg: https://travis-ci.org/okfn/tabular-validator/builds/52039531

I'm seeing a false positive test failure every 5-10 pushes, always due to network issues (connection to http resources like CSVs in tests, and dependencies via pip).

As you know, I'm also running the same tests on Shippable, and I just don't have this happen, ever. 

It is not a big problem, but I'd like to know if it is something you see as Travis users, and/or, if there is some way I can get travis to retry if it has network errors.

**Comment by tryggvib** [comment]
I've seen them occur quite often and feel it's irritating to have to go into the Travis environment to restart the build. It hasn't irritated me enough to investigate whether I can trigger retries.

**Comment by pwalsh** [comment]
Ok, thanks. Good to know that it is something that generally happens on Travis, as I pretty much stopped using it ~ 1 1/2 years ago. So, I'll just continue to ignore false positives for the time being and let things sort out on subsequent pushes.
